### PR TITLE
soci: fix deps

### LINKED ISSUE #5021: soci: Can't detect dependencies (sqlite3, mysql, postgresql, and boost)
### Xmake Version

2.9.4

### Operating System Version and Architecture

Windows 11 Home 23H2

### Describe Bug

When using soci with sqlite3 configuration it doesn't detect the library during lib compilation

### Expected Behavior

It must detect the dependency in order to copy the required headers

### Project Configuration

```lua
add_requires("soci", {configs = {sqlite3 = true, boost = true}})

target("xxx")
    set_kind("binary")
    add_packages("soci")
    ...
```

### Additional Information and Error Logs

CMake says SQLite3 and Boost weren't found

### PR DESCRIPTION
**Pull request by bkmeneguello**
Fixes #5021

### CODE REVIEW

File: packages/s/soci/xmake.lua [hunk 1]
```diff
@@ -45,10 +54,12 @@ package("soci")
...
-            }
-        ]]}, {configs = {languages = "c++14"}}))
+        local includes = {}
+        for _, pkg in ipairs(backends) do
+            if package:config(pkg) then
+                table.insert(includes, "soci/" .. pkg .. "/soci-" .. pkg .. ".h")
+            end
+        end
+        assert(package:has_cxxtypes("soci::session", {configs = {languages = "c++14"}, includes = "soci/soci.h"}))
+        assert(package:has_cxxincludes(includes, {configs = {languages = "c++14"}}))
```
Comment (waruqi) [inline packages/s/soci/xmake.lua:64]: please use check_cxxsnippets.

has_cxxtypes/has_cxxincludes does not check links.

Comment (bkmeneguello) [reply packages/s/soci/xmake.lua]: Fixed

**Review by c8ef — APPROVED** [review]
The current CI failure is because we are using NDK r27 to test against Android packages. To resolve this issue and make the CI happy, you could consider patching the CMakeLists to include a line containing `cmake_policy(SET CMP0057 NEW)`, or you can update the minimum required version of CMake.

Alternatively, we can merge this as it is for now. @waruqi

File: packages/s/soci/xmake.lua [hunk 2]
```diff
@@ -8,24 +8,33 @@ package("soci")
...
+        "postgresql",
+    }
+    for _, backend in ipairs(backends) do
+        add_configs(backend, {description = "Build " .. backend .. " backend", default = false, type = "boolean"})
+    end
+    add_configs("boost", {description = "Enable boost integration", default = false, type = "boolean"})
+    add_configs("visibility", {description = "Enable hiding private symbol using ELF visibility if supported by the platform", default = true, type = "boolean"})
 
-    add_deps("cmake")
+    add_deps("cmake <=3.20", {private = true})
```
Comment (waruqi) [inline packages/s/soci/xmake.lua:27]: why set `private = true`?

**Comment by waruqi** [comment]
we can add on_check to make ci happy.

File: packages/s/soci/xmake.lua (hunk 2 above)
Comment (c8ef) [inline packages/s/soci/xmake.lua:27]: I mean patch the lower bound version at [this link](https://github.com/SOCI/soci/blob/master/CMakeLists.txt#L13), not in the xmake port file.

Comment (bkmeneguello) [reply packages/s/soci/xmake.lua:27]: Because the CMake dependency is transitively propagated to my project, but it should be only necessary to build this library. Is there a better option?

Comment (bkmeneguello) [reply packages/s/soci/xmake.lua]: I made the patch, the checksum works on windows but fails on every other platform.

Comment (SirLynix) [reply packages/s/soci/xmake.lua]: Probably because the checksum was made on a CRLF file, turn the line endings to LF and check it again
