### PR TITLE
Fix `includedirs` for opencv (homebrew)

### LINKED ISSUE #3316: Unexpected opencv `includedirs` when working with opencv installed via homebrew
### Xmake Version

 2.8.6

### Operating System Version and Architecture

macOS Sonoma 14.0

### Describe Bug

The `includedirs` for opencv(>= 4.0) should be something like:
```
includedirs = "/opt/homebrew/Cellar/opencv/4.9.0_3/include/opencv4"
```
but actually it is
```
includedirs = "/opt/homebrew/Cellar/opencv/4.9.0_3/include"
```
which cause the compile error when including almost any header

### Expected Behavior

the `includedir` should be `/opt/homebrew/Cellar/opencv/{version}/include/opencv4` when using homebrew

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")

-- for clangd
add_rules("plugin.compile_commands.autoupdate")

-- cpp version
set_languages("cxx11")

-- opencv
add_requires("opencv")

target("hello")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("opencv")
```

### Additional Information and Error Logs

output of `xrepo fetch -vD opencv`
```
{
  {
    linkdirs = {
      "/opt/homebrew/Cellar/opencv/4.9.0_3/lib"
    },
    links = {
      "opencv_saliency",
      "opencv_photo",
      "opencv_bgsegm",
      "opencv_videoio",
      "opencv_quality",
      "opencv_surface_matching",
      "opencv_datasets",
      "opencv_dnn_objdetect",
      "opencv_viz",
      "opencv_calib3d",
      "opencv_xphoto",
      "opencv_features2d",
      "opencv_img_hash",
      "opencv_dnn",
      "opencv_core",
      "opencv_rgbd",
      "opencv_plot",
      "opencv_freetype",
      "opencv.sfm.simple_pipeline",
      "opencv_imgcodecs",
      "opencv.sfm.multiview",
      "opencv_highgui",
      "opencv_fuzzy",
      "opencv_structured_light",
      "opencv_video",
      "opencv_mcc",
      "opencv_tracking",
      "opencv_superres",
      "opencv_reg",
      "opencv_gapi",
      "opencv_xobjdetect",
      "opencv_text",
      "opencv_ml",
      "opencv_ccalib",
      "opencv_rapid",
      "opencv_objdetect",
      "opencv_stereo",
      "opencv_sfm",
      "opencv_videostab",
      "opencv_aruco",
      "opencv_face",
      "opencv_wechat_qrcode",
      "opencv_alphamat",
      "opencv_stitching",
      "opencv_phase_unwrapping",
      "opencv_xfeatures2d",
      "opencv_ximgproc",
      "ade",
      "opencv_shape",
      "opencv_dnn_superres",
      "opencv_line_descriptor",
      "opencv_dpm",
      "opencv_flann",
      "opencv.sfm.correspondence",
      "opencv_intensity_transform",
      "opencv.sfm.numeric",
      "ittnotify",
      "opencv_hfs",
      "opencv_bioinspired",
      "tegra_hal",
      "opencv_imgproc",
      "opencv_optflow",
      "opencv_bgsegm.4.9.0",
      "opencv_videoio.4.9.0",
      "opencv_mcc.4.9.0",
      "opencv_ml.4.9.0",
      "opencv_structured_light.4.9.0",
      "opencv_ximgproc.4.9.0",
      "opencv_gapi.4.9.0",
      "opencv_photo.4.9.0",
      "opencv_stitching.4.9.0",
      "opencv_intensity_transform.4.9.0",
      "opencv_freetype.4.9.0",
      "opencv_superres.4.9.0",
      "opencv_plot.4.9.0",
      "opencv_stereo.4.9.0",
      "opencv_face.4.9.0",
      "opencv_video.4.9.0",
      "opencv_xfeatures2d.4.9.0",
      "opencv_alphamat.4.9.0",
      "opencv_line_descriptor.4.9.0",
      "opencv_hfs.4.9.0",
      "opencv_viz.4.9.0",
      "opencv_aruco.4.9.0",
      "opencv_datasets.4.9.0",
      "opencv_shape.4.9.0",
      "opencv_bioinspired.4.9.0",
      "opencv_quality.4.9.0",
      "opencv_videostab.4.9.0",
      "opencv_surface_matching.4.9.0",
      "opencv_saliency.4.9.0",
      "opencv_sfm.4.9.0",
      "opencv_calib3d.4.9.0",
      "opencv_dnn_superres.4.9.0",
      "opencv_xobjdetect.4.9.0",
      "opencv_rapid.4.9.0",
      "opencv_dnn.4.9.0",
      "opencv_text.4.9.0",
      "opencv_ccalib.4.9.0",
      "opencv_tracking.4.9.0",
      "opencv_xphoto.4.9.0",
      "opencv_optflow.4.9.0",
      "opencv_objdetect.4.9.0",
      "opencv_imgcodecs.4.9.0",
      "opencv_imgproc.4.9.0",
      "opencv_fuzzy.4.9.0",
      "opencv_phase_unwrapping.4.9.0",
      "opencv_reg.4.9.0",
      "opencv_flann.4.9.0",
      "opencv_dnn_objdetect.4.9.0",
      "opencv_dpm.4.9.0",
      "opencv_wechat_qrcode.4.9.0",
      "opencv_features2d.4.9.0",
      "opencv_core.4.9.0",
      "opencv_rgbd.4.9.0",
      "opencv_img_hash.4.9.0",
      "opencv_highgui.4.9.0"
    },
    includedirs = "/opt/homebrew/Cellar/opencv/4.9.0_3/include"
  }
}
```

### PR DESCRIPTION
**Pull request by y-cg**
Fix #3316

### CODE REVIEW

File: packages/o/opencv/xmake.lua [hunk 1]
```diff
@@ -43,13 +43,35 @@ package("opencv")
...
         add_extsources("pacman::opencv", "apt::libopencv-dev")
         add_syslinks("pthread", "dl")
     elseif is_plat("windows", "mingw") then
         add_syslinks("gdi32", "user32", "glu32", "opengl32", "advapi32", "comdlg32", "ws2_32")
     end
 
+    on_fetch("macosx", function (package, opt)
+        if opt.system and package.find_package then
+            local result
+            for _, name in ipairs({"opencv"}) do
```
Comment (waruqi) [inline packages/o/opencv/xmake.lua:57]: if only one lib, we can remove this for-loop

File: packages/o/opencv/xmake.lua [hunk 2]
```diff
@@ -43,13 +43,33 @@ package("opencv")
...
         add_syslinks("gdi32", "user32", "glu32", "opengl32", "advapi32", "comdlg32", "ws2_32")
     end
 
+    on_fetch("macosx", function (package, opt)
+        if opt.system and package.find_package then
+            local result
+            local pkginfo = package.find_package and package:find_package("brew::" .. "opencv", opt)
+            if pkginfo then
+                if package:version():ge("4.0") then
+                    pkginfo.sysincludedirs = path.join(pkginfo.sysincludedirs, "opencv4")
```
Comment (waruqi) [inline packages/o/opencv/xmake.lua:60]: sysincludedirs may be table, we can not call path.join directly.

File: packages/o/opencv/xmake.lua [hunk 3]
```diff
@@ -43,13 +43,33 @@ package("opencv")
...
+                end
+                if not result then
+                    result = table.copy(pkginfo)
```
Comment (waruqi) [inline packages/o/opencv/xmake.lua:63]: we can use result instead of pkginfo, and remove table.copy

File: packages/o/opencv/xmake.lua [hunk 4]
```diff
@@ -43,13 +43,33 @@ package("opencv")
...
+        add_extsources("brew::opencv")
     elseif is_plat("linux") then
         add_extsources("pacman::opencv", "apt::libopencv-dev")
         add_syslinks("pthread", "dl")
     elseif is_plat("windows", "mingw") then
         add_syslinks("gdi32", "user32", "glu32", "opengl32", "advapi32", "comdlg32", "ws2_32")
     end
 
+    on_fetch("macosx", function (package, opt)
+        if opt.system and package.find_package then
```
Comment (waruqi) [inline packages/o/opencv/xmake.lua:55]: remove `and package.find_package`
